import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className='h-screen w-screen bg-neutral-900 items-center justify-center flex flex-col'>
        <h1 className='text-6xl text-neutral-100'> Hello Tailwind! </h1>
      </main>
    </>
  );
}
